des:
	mkdir -p bin && gcc -g -o bin/des des.c

des_test:
	mkdir -p bin && gcc -g -o bin/des_test des_test.c

endian:
	mkdir -p bin && gcc -g -o bin/endian endian.c

scratch:
	mkdir -p bin && gcc -g -o bin/scratch scratch.c
