http_client:
	mkdir -p bin && gcc -g -o bin/http_client base64_lib.c http.c

base64:
	mkdir -p bin && gcc -g -o bin/base64 base64.c -lm

webserver:
	mkdir -p bin && gcc -g -o bin/webserver webserver.c

